### ISSUE TITLE
Failing perft

### ISSUE THREAD

**Issue by GoldenChrysus** [TimHanewich/TimHanewich.Chess#1]
I am trying to test this library's move generation for viability, but it is failing starting from a depth of 1. It is including castling as a valid move for white starting from the initial FEN (classical chess). 

Version: 0.3.0 from NuGet
(I assume this may be resolved as there are legality commits dated after the release of 0.3.0.)

These moves are returned as valid by `BoardPosition.AvailableMoves()`:
```
A2 --> A3
A2 --> A4
B2 --> B3
B2 --> B4
C2 --> C3
C2 --> C4
D2 --> D3
D2 --> D4
E2 --> E3
E2 --> E4
F2 --> F3
F2 --> F4
G2 --> G3
G2 --> G4
H2 --> H3
H2 --> H4
B1 --> A3
B1 --> C3
G1 --> F3
G1 --> H3
O-O
O-O-O
```

Information on perft is available at: https://www.chessprogramming.org/Perft
And the list of expected position counts from the initial FEN per depth is available at: https://www.chessprogramming.org/Perft_Results

Edit: I have a repo setup [here](https://github.com/GoldenChrysus/ChessPerft) with very basic test logic you can use if you want. Also notable though outside the scope of this issue is that I encountered issues when trying to reverse moves (various illegal move errors), so I instead instantiated the board with its original FEN, after the recursion.

**Comment by TimHanewich** [comment]
Hello @GoldenChrysus , thanks for bringing this up. Indeed, this has just recently been solved in the new commits you noticed since the release of version 0.3.0. I just packaged up the current code and published [version 0.4.0](https://www.nuget.org/packages/TimHanewich.Chess/0.4.0). I verified the starting position castling that you pointed out is not an issue in this new version. 

However, this isn't to say that the move generation is perfect, I'm certain it is not. I created a [known issues section in the readme](https://github.com/TimHanewich/TimHanewich.Chess#known-issues) where I will continue to document issues/areas that still need to be developed. You can see one of them relates to castling at the moment.
